# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1ada213f50b5a9c0caccae08f5e0531d432777da1e51ea86fa0287c51100e686dfaf94446340f2b26b6eb5778ad0671b613652334c1eee26fe3624c09939670

test:
  secret_key_base: 801f143eefd06fd39b5ce7460cc061e0294752fbef1dc9d462686b42ae56aa7d7718e4fbb8086808040e99658394f4a7875e84078fa31da95d91bf504b4e7b8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
